### ISSUE TITLE
Error when running the app.

### ISSUE THREAD

**Issue by usmangurowa** [mrzachnugent/rn-ui-inspired-by-shadcn#5]
@mrzachnugent Great work building this awesome project.

I encounter an error when running locally, i use "yarn start" since already there is a start script in the package.json. However, when I scan the QR code to open on the Expo Go app (android) I get an error that says:

```
tailwindcss(native) rebuilding... tailwindcss(native) is taking a long time to build, please read https://tailwindcss.com/docs/content-configuration#pattern-recommendations to speed up your build time

Error running TailwindCSS CLI, please run the CLI manually to see the error.
Command used:  node C:\Users\hp victus\Desktop\shadcn-expo\node_modules\tailwindcss\lib\cli.js --input "C:\Users\hp victus\Desktop\shadcn-expo\global.css" --output "C:\Users\hp victus\Desktop\shadcn-expo\node_modules\.cache\nativewind\global.css.native.css" --watch
```   

![image](https://github.com/mrzachnugent/rn-ui-inspired-by-shadcn/assets/55620906/cb51c9c0-35db-485b-9366-a21c7a73199d)

**Comment by mrzachnugent** [comment]
@usmangurowa I used `npm` for this project so it created a `package-lock.json` and it might be causing issues with the yarn.lock created from using `yarn`.

You can try to delete your `yarn.lock` file, delete your `node_modules` folder, use `npm i` in your terminal and start it with `npm run start`.

Let me know if that helps.

**Comment by mrzachnugent** [comment]
This might be an issue with [nativewind](https://github.com/marklawlor/nativewind). I am using a beta version, but I am able to use Expo Go on my android device. So it should work.

It would also be related to the `package-lock.json` and the `yarn.lock` created from using `yarn`.
Can you try deleting your `yarn.lock` and your node modules. Then using `npm` to install the deps and to start the project?

Let me know if that works.

**Comment by usmangurowa** [comment]
Hi @mrzachnugent i was able to do exactly what you said and the app ran without any errors. I will love to contribute, let me know if you are looking for contributors. Thanks.
